### PR TITLE
Adds more types for the customer attribute

### PR DESCRIPTION
**Pull request by bdcannon**

### CODE REVIEW

**Comment by stuartsharpe11** [comment]
Just to make sure I'm understanding correctly, you mean we should just remove the copy button, right?  Here's how I'm interpreting that, but just not sure if I'm right:
screen shot 2018-05-16 at 6 32 40 am

**Comment by bdcannon** [comment]
The copy button is a great idea from a feature.

I was talking about these lines.
https://github.com/stuartsharpe11/chrome-react-extension/blob/component/lead-attribute/src/components/lead-attribute.jsx#L37-L51

Instead of having a function for each thing we change like the icon or the placeholder, we should just have one function returning all the different stylings

```javascript
getAttributeStyles(type){
  case 'email' : return {icon: ..., placeholder: ...}
  case 'phone' : return {icon: ..., placeholder: ... }
}
``` 

I was just talking. I think it would be easier to maintain.

**Comment by stuartsharpe11** [comment]
Ok, gotchta. Because the methods are pretty much the same we can pass through single attributes. 

I could be overcomplicating this, but would that then look something like an if/else statement within a single function --> if there's an email or phone, return available email or phone, else return "no available email" or "no available phone number"

**Comment by bdcannon** [comment]
> if/else statement within a single function --> if there's an email or phone, return available email or phone, else return "no available email" or "no available phone number"

I think when we get to scraping the page it will be something like that. Search the page for elements with tags or something that identifies them as being an email, address, skill whatever. We'll probably have a method for each kind of attribute we support. Like `findEmails()` and that will render an email attribute with the prop set like `<LeadAttribute type={'email'} value={'ben@flexfits.com'} />`

**Comment by bdcannon** [comment]
Squashed those two methods into one 

https://github.com/stuartsharpe11/chrome-react-extension/blob/96f9836c22c38c24d6f3487c292e513f16d68f84/src/components/lead-attribute.jsx#L39-L54

**Pull request merged**
